FROM alpine:3.19.1

# Install some dependencies
RUN apk add --no-cache \
    bash \
    curl \
    git \
    jq \
    openssh-client \
    python3 \
    py3-pip \
    rsync \
    zip

# Sleep for 10 seconds to show caching
RUN sleep 10
