name: Main Branch
on:
  push:
    branches:
      - main

permissions:
  id-token: write # required for OIDC role assumption

jobs:
  cdk-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Mask AWS Account Number
        run: echo "::add-mask::${{ secrets.CDK_DEFAULT_ACCOUNT }}"
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - run: npm ci
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CDK_DEPLOY_ROLE_ARN }}
          aws-region: us-west-2
      # buildx is required to support caching docker layers using the GitHub Actions cache backend
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          use: true
      # This is required for the `gha` cache to work with CDK DockerImageAssets
      # See https://docs.docker.com/build/cache/backends/gha/#authentication
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      - name: CDK Deploy
        run: npx cdk deploy --require-approval never '**'
        env:
          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
